### ISSUE TITLE
Unable to refer artifact from a directory above the root directory in path parameter

### ISSUE THREAD

**Issue by promad02** [SAP/cloud-mta-build-tool#646]
My mta file is stored in A/B/mta.yaml

For a service instance, I need to refer a file A/xs-security.json.

I have provided the path parameter as 
path
  -../xs-security.json

But this isn't working.
I can't see the xs-security.json in the archive file. Also when I am trying to deploy the file I am getting the following error:
`must use only Unix separators "/", but contains Windows separators "\"`

This is weird as I am using "/" and not "\"

**Comment by katunin-ng** [comment]
Hi,

Usage of ".." in path properties is not allowed by the [MTA specification](https://www.sap.com/documents/2016/06/e2f618e4-757c-0010-82c7-eda71af511fa.html): 

_d.If the descriptor key path represents a file system path, then it must be interpreted as relative paths and must be path-traversal-safe.  This means, the path must then not begin with a slash "/",or backslash "\", or two periods ".."._

But I took this issue to security experts for additional validation. If they confirm, we will make sure that this error is clearly reported by the tool. Otherwise, package the json file as expected into the MTA archive.

Meanwhile, could you please elaborate on why you have such setup in your project?
Is it possible to place the xs-security.json file into the same directory where the MTA descriptor is located?

The issue of the "_must use only Unix separators "/", but contains Windows separators "\"_" will be fixed in the next MBT version. It is not related to the first problem (".." usage), it was reproducible even if one had a valid path with '/' in mta.yaml, e.g. "./A/B/xs-secutity.json".

Regards
Natalia

**Comment by tal-sapan** [comment]
Hi,

The windows separator issue was fixed in release 1.0.7.

Best regards,
Tal

**Comment by promad02** [comment]
Hi,

I will explain the reason of such a setup. We have an umbrella project A
under which there are several modules. We want to have a central
xs-security.json at umbrella level for each module to refer for ease of
maintenance and also uniformity. Is there any alternative to achieve this?

Regards,
Prodipto

**Comment by katunin-ng** [comment]
Hi Prodipto,

Thank you for your response.
But I need additional clarifications.
If you say that your project root is located in A and modules are located in the inner directories, why mta.yaml is not located in this directory as well?
Do you consider A to be an MTA project or each your module is a separate MTA project that you want to build and deploy independently?

Regards
Natalia

**Comment by promad02** [comment]
Hi,

Yes you are right. Each module of A viz, B is also a mta project.

Regards,
Prodipto

**Comment by katunin-ng** [comment]
HI Prodipto,

You have a very special setup. And I still need to understand it better in order to provide you with the best solution. 
Do all these projects: umbrella project A and inner projects B, etc. reside in a single git repository?
Are they part of a single solution? What is their lifecycle: do you usually build and deploy them together? Do you define cross-MTA dependency between them? Do they share the same instance of uaa service (so it can be created once via one of the inner MTAs)?  How do you arrange a CI process for these projects? etc
Probably we can discuss these topics in a meeting? If you are interested, please just drop me an mail: natalia.katunin@sap.com.

Regards
Natalia

**Comment by katunin-ng** [comment]
Hi Prodipto,

I am closing the issue due to no reply.
If needed please re-open and answer the questions above.

Regards
Natalia

**Comment by socenmarc** [comment]
Hi,
I got this error in version 1.0.11.
My path was ./mtconfig/config.json and I got the following error:

> Error processing MTA archive: com.sap.cloud.lm.sl.cf.persistence.services.FileStorageException: com.sap.cloud.lm.sl.common.ContentException: Path "mtconfig\config.json" must use only Unix separators "/", but contains Windows separators "\"

I moved the file and works fine with ./config.json

Regards,
Marc

**Comment by tal-sapan** [comment]
Hi @socenmarc,

Version 1.0.7 was released after you opened the issue.
Did you reproduce the issue with the Windows path separators with version 1.0.11? Could you try again with the newest version (1.0.14) and make sure that it's really the version used for the build (the version is printed at the start of the build)?

Regards,
Tal
