### ISSUE TITLE
html5 module deployment fails with java heap memory error after building with MBT builder.

### ISSUE THREAD

**Issue by kiranbadala** [SAP/cloud-mta-build-tool#679]
Do you want to request a feature or report a bug?
Report a bug

Please provide the following info:

  - MBT Version:1.0.8
  - OS Version: Windows 10
  - If possible, provide a link to the project.
https://github.wdf.sap.corp/IndustryCloudBusinessServices/BCM_Repo/tree/feature

Steps to Reproduce:

1. Add builder parameters( supported-platforms: [CF],  build-result: dist) as suggested in documentation.
2. Build using the MBT builder
3. Chack in the failed html5 module logs file.

**Comment by katunin-ng** [comment]
Hi,

The working and problematic mtars are required to investigate the issue.
We sent you a mail with details on where to upload them.

Regards
Natalia

**Comment by allaVolkov** [comment]
Hi Kiran Kumar,

Documentation of Migration suggests the following:
Packaging of HTML5 modules in deploy_mode=html5-repo You need to update your mta.yaml file to exclude html5 modules from the resulting MTA archive and configure the build result folder. In order to do that, add the following to the build-parameters section for each module of this type:
   build-parameters:
      supported-platforms: []
      build-result: dist

Please set supported platforms in your html5 modules to [].

Regards,
Alla
