### ISSUE TITLE
Enable ssh in cloud foundry modules

### ISSUE THREAD

**Issue by kushsharma1001** [SAP/cloud-mta-build-tool#734]
Hi, 
I need more info about enabling ssh by default for a CF module. I am aware of the fact that we can add a new parameter with "enable-ssh:true". What will be the deployment behaviour if space level ssh is not allowed? Will the deployment itself fail?

**Comment by katunin-ng** [comment]
Hi,

This repository is for the MTA build tool. Since your question relates to the deployment I suggest you use different channels:  the cloud-foundry slack: [#multiapps-dev](https://cloudfoundry.slack.com/archives/C9V0Z8ZPF) or directly create and track a [github issue](https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/issues) on the OSS project.

Regards
Natalia
