### ISSUE TITLE
SAP cloud cockpit connect to jenkins 

### ISSUE THREAD

**Issue by sri179970** [SAP/cloud-mta-build-tool#770]
SAP cloud cockpit connect to jenkins 

Hi 

we are trying  to connect sapwebIDE to Jenkins, we have git repositories in SAP could platform cockpit  neo environment which are used for HAAS (Cloud Foundry) development.
Now we want to automate build and deploy code from these git repositories maybe using Jenkins
 
Did anyone connected SAP could platform cockpit  to Jenkins, github, maven, or dockers? For this build and deploy process 

We tired transport management tool  however to build mtar file and upload to transport management tool?

**Comment by sri179970** [comment]
we are trying to connect sapwebIDE to Jenkins, we have git repositories in SAP could platform cockpit neo environment which are used for HAAS (Cloud Foundry) development.
Now we want to automate build and deploy code from these git repositories maybe using Jenkins

Did anyone connected SAP could platform cockpit to Jenkins, github, maven, or dockers? For this build and deploy process

We tired transport management tool however to build mtar file and upload to transport management tool?

**Comment by katunin-ng** [comment]
Hi,

Please check this guide https://help.sap.com/viewer/product/CICD_OVERVIEW/Cloud/en-US?task=discover_task that describes different solutions for CI/CD. 

On that page, you can also find a link to ask additional questions on the topic (search for Making an Impact string).

I am closing this issue here, as it does not relate the Cloud MTA Build.

Regards
Natalia
