### ISSUE TITLE
Reduce build time for large project

### ISSUE THREAD

**Issue by PeterSevr** [SAP/cloud-mta-build-tool#805]
We have more than 150 MTA builds a day, and it's growing..., we made some optimization to our CI, but for a large MTA project, the build time is taking a long time. Our team's goal is to reduce it (currently, three devs are working on it). 
We know that this is not a simple task to handle; however, we want to dive deep and run some micro-optimizations to provide better results. Could you please provide help/advice from your side on how we can achieve that?

**Comment by tal-sapan** [comment]
Hi,

There are 2 things you could consider for optimization:
1. Building the modules in parallel using `-m` and `-j` options, see [the documentation](https://sap.github.io/cloud-mta-build-tool/usage/#one-step-build).
1. Optimizing the build command of each module, which you can do by changing the command as you like with a [custom builder](https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-the-custom-builder).

Let me know if this helps.

Best regards,
Tal

**Comment by katunin-ng** [comment]
Hi, 

As Tal wrote above, please consider using an option for module parallel build: mbt build -m=verbose -j=8 (see here for the details: https://sap.github.io/cloud-mta-build-tool/usage/#one-step-build). This build command allows building several independent modules simultaneously. Note: these command options are BETA features and in some future releases we are planning to change this interface. However, based on your feedback we can change the priorities and provide a stable interface sooner.

Do your problematic projects contain multiple html5 modules? If "npm install" command is run for each module, the project build indeed takes very long. It is possible to configure the build process so that "npm install" command that downloads the required dependencies that are common for all html5 modules is run once as part of "before-all" build step. Let me know if this is your case and I will provide more details about this option.

Regards
Natalia

**Comment by PeterSevr** [comment]
We are already using custom builders which indeed help us to reduce the build time for similar modules. I asked the team to try the one command build and will update soon.

**Comment by PeterSevr** [comment]
My team runs several builds today, and the results are fantastic! 
In some projects, the build time was reduced by 30%- 50%. (others have some internal deps and build errors that we need to solve) 
We are exploring how this magic works under the hood as we want to reuse some of the patterns in our dev too.
 It seems that you took the `make` capabilities to the edge. 
This is out-of-the-box thinking for a complex problem, which is neat
You save my team lot of time.
 Kudos!

**Comment by tal-sapan** [comment]
That's great to hear, glad this solution worked for you.
